version: '3'

services:
  nginx:
    build: nginx
    links:
        - socket1:socket1
        - socket2:socket2
    ports:
        - "9999:9061"
        - "9992:9002"
    container_name: nginx

  gameserver:
    build:
      context: game-service
      dockerfile: Dockerfile
    container_name: server
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      - APP_NAME=china
      - API_HISTORY_URL=https://api.cxz777.com/api/history
      - SERVER_HOST=112.198.15.68
      - SERVER_PORT=8000
      - REDIS_HOST=112.198.15.68
      - REDIS_PORT=6666
      - REDIS_PASSWORD=bfd3v3l0p3r1@
      - DB_HOST=112.198.15.68
      - DB_USER=webuser
      - DB_PORT=3333
      - DB_PASS=webuser1@
      - BC_DB_NAME=baccarat
      - DT_DB_NAME=dragontiger
      - POKER_DB_NAME=poker
      - SICBO_DB_NAME=sicbo
      - NIHTAN_DB_NAME=nihtan_api
    ports:
      - "8881:8000"
    networks:
      - backend
    depends_on:
      - db
      - redis

  socket1:
    build:
      context: socket-service
      dockerfile: Dockerfile
    container_name: socket1
    environment:
      - APP_NAME=socket1
      - APP_HOST=112.198.15.68
      - HTTP_PORT=9000
      - GAME_SERVER=game-servers
      - REDIS_HOST=112.198.15.68
      - REDIS_PORT=6666
      - REDIS_PASSWORD=bfd3v3l0p3r1@
      - GAME_SERVER_REDIS_PORT=6666
      - GAME_SERVER_REDIS_HOST=112.198.15.68
      - GAME_SERVER_REDIS_PASSWORD=bfd3v3l0p3r1@
      - SHOULD_EMIT=1
      - SHOULD_UPDATE_AND_EMIT=1

    ports:
      - "9001:9000"
    links:
      - redis
    depends_on:
      - redis

  socket2:
    build:
      context: socket-service
      dockerfile: Dockerfile
    container_name: socket2
    environment:
      - APP_NAME=socket2
      - APP_HOST=112.198.15.68
      - HTTP_PORT=9004
      - GAME_SERVER=game-servers
      - REDIS_HOST=112.198.15.68
      - REDIS_PORT=6666
      - REDIS_PASSWORD=bfd3v3l0p3r1@
      - GAME_SERVER_REDIS_PORT=6666
      - GAME_SERVER_REDIS_HOST=112.198.15.68
      - GAME_SERVER_REDIS_PASSWORD=bfd3v3l0p3r1@
      - SHOULD_EMIT=0
      - SHOULD_UPDATE_AND_EMIT=0

    ports:
      - "9004:9004"
    links:
      - redis
    depends_on:
      - redis

  db:
    image: mysql:5.7
    ports:
      - "3333:3306"
    command: mysqld --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: "bfd3v3l0p3r1@"
      MYSQL_USER: "webuser"
      MYSQL_PASSWORD: "webuser1@"
    networks:
      - backend
  redis:
    image: redis:4-alpine
    command: redis-server --requirepass bfd3v3l0p3r1@
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    container_name: redis
    #network_mode: host
    ports:
      - "6666:6379"

  redis2:
    image: redis:4-alpine
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    container_name: redis2
    ports:
      - "5555:6379"

  redis3:
    image: redis:4-alpine
    volumes:
      - ./redis.conf:/usr/local/etc/redis/refis.conf
    container_name: redis3
    ports:
      - "7777:6379"

networks:
  backend:
