FROM nginx

# File Author / Maintainer
MAINTAINER Shinji Escorido

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx
#.confroot@iZj6c07wau0pbtiqw3xkemZ:/d/regions/nginx# vim Dockerfile
# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER Shinji Escorido

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf
